# Generated by Django 4.1 on 2022-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_image_app', '0002_alter_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateField(auto_now=True),
        ),
    ]
